# Generated by Django 4.2 on 2024-06-29 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lorca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=60, null=True)),
                ('table', models.SmallIntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('state', models.SmallIntegerField(choices=[(1, 'not confirmed'), (2, 'confirmed'), (3, 'ready')], default=1)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BasketLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='basket_lines', to='basket.basket')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='lorca.item')),
            ],
        ),
    ]
